name: 'deel'
version: '1.0.0'
config-version: 2

profile: 'deel'

model-paths: ["models"]
seed-paths:  ["seeds"]
macro-paths: ["macros"]
test-paths:  ["tests"]

target-path:  "target"
clean-targets: ["target", "dbt_packages"]


models:
  deel:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table